# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BEER_DIM',
            fields=[
                ('BEER_ID', models.CharField(db_column='BEER_ID', max_length=6, primary_key=True, serialize=False)),
                ('CATEGORY_ID', models.IntegerField(blank=True, db_column='CATEGORY_ID', null=True)),
                ('STYLE_ID', models.IntegerField(blank=True, db_column='STYLE_ID', null=True)),
                ('GLASS_ID', models.IntegerField(blank=True, db_column='GLASS_ID', null=True)),
                ('NAME', models.CharField(db_column='NAME', max_length=100)),
                ('NAME_DISPLAY', models.CharField(blank=True, db_column='NAME_DISPLAY', max_length=100, null=True)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=2000, null=True)),
                ('ABV', models.DecimalField(blank=True, db_column='ABV', decimal_places=2, max_digits=5, null=True)),
                ('IBU', models.DecimalField(blank=True, db_column='IBU', decimal_places=4, max_digits=10, null=True)),
                ('SRM_ID', models.IntegerField(blank=True, db_column='SRM_ID', null=True)),
                ('AVAILABLE_ID', models.IntegerField(blank=True, db_column='AVAILABLE_ID', null=True)),
                ('IS_ORGANIC', models.CharField(blank=True, db_column='IS_ORAGNIC', max_length=1, null=True)),
                ('STATUS', models.CharField(blank=True, db_column='STATUS', max_length=50, null=True)),
                ('STATUS_DISPLAY', models.CharField(blank=True, db_column='STATUS_DISPLAY', max_length=50, null=True)),
                ('SERVING_TEMP', models.CharField(blank=True, db_column='SERVING_TEMP', max_length=10, null=True)),
                ('SERVING_TEMP_DISPLAY', models.CharField(blank=True, db_column='SERVING_TEMP_DISPLAY', max_length=50, null=True)),
                ('LABEL_SMALL', models.CharField(blank=True, db_column='LABEL_SMALL', max_length=100, null=True)),
                ('LABEL_MEDIUM', models.CharField(blank=True, db_column='LABEL_MEDIUM', max_length=100, null=True)),
                ('LABEL_LARGE', models.CharField(blank=True, db_column='LABEL_LARGE', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPECIALS_HDR_FCT',
            fields=[
                ('SPECIAL_HDR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SPECIAL_HDR_DESC', models.CharField(blank=True, max_length=100, null=True)),
                ('START_TIME', models.TimeField(blank=True, null=True)),
                ('END_TIME', models.TimeField(blank=True, null=True)),
                ('DAY_MON_FLG', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('DAY_TUE_FLG', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('DAY_WED_FLG', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('DAY_THUR_FLG', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('DAY_FRI_FLG', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('DAY_SAT_FLG', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('DAY_SUN_FLG', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SPECIALS_LN_FCT',
            fields=[
                ('SPECIAL_LN_ID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('SERVING_SIZE', models.IntegerField(default=0)),
                ('PRICE_AMT', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('BEER_ID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='drinkinfo.BEER_DIM')),
                ('SPECIAL_HDR_ID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='drinkinfo.SPECIALS_HDR_FCT')),
            ],
        ),
    ]
