# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOCATION_FCT',
            fields=[
                ('PLACE_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('PLACE_NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='specials_hdr_fct',
            name='PLACE_ID',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='drinkinfo.LOCATION_FCT'),
        ),
    ]
