# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0002_auto_20160827_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_dim',
            name='CREATED_AT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beer_dim',
            name='UPDATED_AT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='specials_hdr_fct',
            name='CREATED_AT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='specials_hdr_fct',
            name='UPDATED_AT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='specials_ln_fct',
            name='CREATED_AT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='specials_ln_fct',
            name='UPDATED_AT',
            field=models.DateTimeField(null=True),
        ),
    ]
