# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0003_auto_20160827_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer_dim',
            name='CREATED_AT',
        ),
        migrations.RemoveField(
            model_name='beer_dim',
            name='UPDATED_AT',
        ),
    ]
