# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0004_auto_20160827_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specials_hdr_fct',
            old_name='CREATED_AT',
            new_name='CREATE_DATE',
        ),
        migrations.RenameField(
            model_name='specials_hdr_fct',
            old_name='UPDATED_AT',
            new_name='UPDATE_DATE',
        ),
        migrations.RenameField(
            model_name='specials_ln_fct',
            old_name='CREATED_AT',
            new_name='CREATE_DATE',
        ),
        migrations.RenameField(
            model_name='specials_ln_fct',
            old_name='UPDATED_AT',
            new_name='UPDATE_DATE',
        ),
        migrations.AddField(
            model_name='beer_dim',
            name='CREATE_DATE',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beer_dim',
            name='UPDATE_DATE',
            field=models.DateTimeField(null=True),
        ),
    ]
