# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0005_auto_20160827_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='DAY_MON_FLG',
            field=models.BooleanField(default=False),
        ),
    ]
