# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0006_auto_20160831_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='DAY_FRI_FLG',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='DAY_SAT_FLG',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='DAY_SUN_FLG',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='DAY_THUR_FLG',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='DAY_TUE_FLG',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='DAY_WED_FLG',
            field=models.BooleanField(default=False),
        ),
    ]
