# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0007_auto_20160831_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='START_TIME',
            field=models.TimeField(blank=True, choices=[('12:00:00', '12:00 PM')], null=True),
        ),
    ]
