# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0010_auto_20160831_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='END_TIME',
            field=models.TimeField(choices=[('12:00:00', '12:00:00')], default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='START_TIME',
            field=models.TimeField(choices=[('12:00:00', '12:00:00')], default='12:00:00'),
        ),
    ]
