# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0011_auto_20160831_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='END_TIME',
            field=models.TimeField(choices=[(datetime.time(15, 0), '3 PM')], default=datetime.time(15, 0)),
        ),
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='START_TIME',
            field=models.TimeField(choices=[(datetime.time(15, 0), '3 PM')], default=datetime.time(0, 0)),
        ),
    ]
