# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0012_auto_20160831_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='END_TIME',
            field=models.TimeField(choices=[(datetime.time(0, 0), '12 AM'), (datetime.time(1, 0), '1 AM'), (datetime.time(1, 0), '1 AM'), (datetime.time(3, 0), '3 AM'), (datetime.time(4, 0), '4 AM'), (datetime.time(5, 0), '5 AM'), (datetime.time(6, 0), '6 AM'), (datetime.time(7, 0), '7 AM'), (datetime.time(8, 0), '8 AM'), (datetime.time(9, 0), '9 AM'), (datetime.time(10, 0), '10 AM'), (datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 PM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM'), (datetime.time(18, 0), '6 PM'), (datetime.time(19, 0), '7 PM'), (datetime.time(20, 0), '8 PM'), (datetime.time(21, 0), '9 PM'), (datetime.time(22, 0), '10 PM'), (datetime.time(23, 0), '11 PM')], default=datetime.time(23, 0)),
        ),
        migrations.AlterField(
            model_name='specials_hdr_fct',
            name='START_TIME',
            field=models.TimeField(choices=[(datetime.time(0, 0), '12 AM'), (datetime.time(1, 0), '1 AM'), (datetime.time(1, 0), '1 AM'), (datetime.time(3, 0), '3 AM'), (datetime.time(4, 0), '4 AM'), (datetime.time(5, 0), '5 AM'), (datetime.time(6, 0), '6 AM'), (datetime.time(7, 0), '7 AM'), (datetime.time(8, 0), '8 AM'), (datetime.time(9, 0), '9 AM'), (datetime.time(10, 0), '10 AM'), (datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 PM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM'), (datetime.time(18, 0), '6 PM'), (datetime.time(19, 0), '7 PM'), (datetime.time(20, 0), '8 PM'), (datetime.time(21, 0), '9 PM'), (datetime.time(22, 0), '10 PM'), (datetime.time(23, 0), '11 PM')], default=datetime.time(0, 0)),
        ),
    ]
