# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0013_auto_20160831_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specials_hdr_fct',
            old_name='DAY_THUR_FLG',
            new_name='DAY_THU_FLG',
        ),
    ]
