# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0014_auto_20160901_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_fct',
            name='LAT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location_fct',
            name='LNG',
            field=models.FloatField(null=True),
        ),
    ]
