# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0015_auto_20160902_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOCATION_DIM',
            fields=[
                ('LOCATION_KEY', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('PLACE_ID', models.CharField(max_length=100)),
                ('PLACE_NAME', models.CharField(max_length=50)),
            ],
        ),
    ]
