# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinkinfo', '0016_location_dim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specials_hdr_fct',
            name='PLACE_ID',
        ),
        migrations.AddField(
            model_name='specials_hdr_fct',
            name='LOCATION_KEY',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='drinkinfo.LOCATION_DIM'),
        ),
    ]
